version: 2.1

orbs:
  ruby: circleci/ruby@3.2.2
  node: circleci/node@16.17.1
jobs:
  build:
    docker:
      - image: circleci/default

    working_directory: ~/app

    environment:
      RAILS_ENV: test
      NODE_ENV: test

    steps:
      - checkout

      - ruby/install
      - node/install

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            gem install bundler
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
            yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
            - ./node_modules

      - run:
          name: Database setup
          command: |
            bundle exec rails db:create db:schema:load --trace

      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
